BR_STOCKS = [
"PETR4.SA","ITSA4.SA","ITUB4.SA","CMIG4.SA",
"CSAN3.SA","ISAE4.SA","ABEV3.SA","VALE3.SA",
"BBAS3.SA","SAPR4.SA","PRIO3.SA","KLBN4.SA",
"RAPT4.SA","SIMH3.SA","DIVD3.SA","LFTB11.SA"
]

MACRO = [
"USDBRL=X",
"^TNX",
"EMB"
]

CRYPTO = [
"BTC-USD",
"TOTAL3-USD"
]

ALL_TICKERS = BR_STOCKS + MACRO + CRYPTO
